parameters:
#    mesd_swiftmailer.example.class: Mesd\SwiftmailerBundle\Example

services:
#    mesd_swiftmailer.example:
#        class: %mesd_swiftmailer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
